#!/usr/bin/env python3

import boto3
import io
import re

s3 = boto3.resource('s3')
ec2 = boto3.resource('ec2', region_name='us-east-1')

instances = ec2.instances.filter(
    Filters=[{'Name': 'instance-state-name', 'Values': ['running']}])
strData = ""

for a, instance in enumerate(instances):
    for tag_list in instance.tags:
        for a in tag_list:
            if tag_list[a] == 'Email' and re.match(r"^[a-zA-Z0-9_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+", tag_list['Value']):
                list_ow = instance.id + ' : ' + tag_list['Value']
                strData += list_ow + "\n"

s3.Bucket('<<ENTER-S3-Bucket-Name>>').put_object(Key='report.txt', Body=strData)
